### ISSUE TITLE
UserController

### ISSUE THREAD

**Issue by AbaturDev** [AbaturDev/WrocRide#13]
Mysle ze mozemy zrobic user kontroler, gdzie bedzie mozna zmienic swoje dane uzytkownika jakies haslo/nr telfonu immie nazwisko itp (bez emailu). 
Mozna dodać ze mozemy zobaczyc swoj profil - swoje dane aktualne (ale tylko swoje wiec autoryzacja po aktualnie zalogowanym uzytkowniku)

najwazniejsze tu bedzie poza tym getem i putem to zaimplementowac tego currentUsera zeby mozna bylo po tym autoryzować ta klase. Wiem ze chyba fullstack mial o tym filmik,

**Comment by AbaturDev** [comment]
Wiesz ten get cos w stylu /me na koncu

**Comment by AbaturDev** [comment]
1. UserContext - serwis gdzie mozna pobrac liste claimow uzytkownika (do autoryzacji)
2. UserController + serwis - pobranie inofrmacji o sobie samym i aktualizacja ich(duza opcjonalnosc patrz carUpdate).

**Comment by AbaturDev** [comment]
A i najwazniejsze to w userContext zeb byl getUserId!!!!

**Comment by AbaturDev** [comment]
@Havkarr zmiana planu!!!
Zrob tego user controllera (a potem admina) itp a ten usercontext to olej bo to 2 linie kodu a ja to mam

**Comment by Havkarr** [comment]
Got it!

**Comment by Havkarr** [comment]
Udało mi się to w końcu napisać. Testowałem to w postmanie i działa, natomiast cały casz nie mogę odpalić tego swaggera. Musimy ustalić wytyczne aby walidować zmianę hasła (ile znaków, minimalna długość, itp). Dodatkowo myślałem, żeby dodać nowy błąd który by się aktywował gdyby user nie był zalogowany np: NotLoggedIn czy coś. Czekam na twój feedback.

**Comment by Havkarr** [comment]
Nie tworzę pull requesta dopóki nie rozwiąże problemu ze swaggerem.

**Comment by Havkarr** [comment]
Dodałem ścieżkę w PUT do DriverDecision w RideControllerze aby swagger działał.
